name: Teaming
main: Teaming\Main
version: 2.0.1
api: 5.0.0
author: ZyberPE

commands:
  team:
    description: Team commands
    usage: "/team help"
    permission: teaming.use

permissions:
  teaming.use:
    default: true
