name: Teaming
main: Teaming\Main
version: 2.1.0
api: 5.0.0
author: ZyberPE

commands:
  team:
    description: Team system
    usage: "/team help"
    permission: teaming.use

permissions:
  teaming.use:
    default: true
